# -*- coding: utf-8 -*-
"""CA1-Ex3.3-111401546.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12HRVij3rJ-NeB_EGoT7aZ25aF1DGnxDD
"""

## 企管四 111401546 胡予娟
## ------------------------------
##  < Exercise 3.3 > :  利用巢狀迴圈 (Nested Loop) 產生輸出結果
## ------------------------------
letters='ABCDEFGHIJ'      ## 0123456789是index的部分
for i in range(10):
    for j in range(10):
        print(letters[(j+i)%10], end='')

    print(end="\n")         #  跳至下一行