# -*- coding: utf-8 -*-
"""CA2-Queue or Stack -111401546.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REKebDoNPTBBIIdwD7nop1vknBHqFdzv
"""

#企管四 111401546 胡予娟
def Queue_or_Stack(qors, prompt=' Push data (type null if done): '):
    '''
    qors = 0  : Queue
    qors = -1 : Stack
    '''

    data = []

    while True:
        top = input(prompt)

        if top in ('n', 'nu', 'nul', 'null'):
            break
        else:
            data.append(top)

    print('\nWithin data:', data, end='\n\n')

    if qors == -1:
        print('<<< Pop the data --> LIFO : Last-In-First-Out >>>')
    elif qors == 0:
        print('<<< Pop the data --> FIFO : First-In-First-Out >>>')
    else:
        print('<<< Invalid mode: use 0 for Queue or -1 for Stack >>>')
        return

    for _ in range(len(data)):
        print('pop data :', data.pop(qors))

    print('\n******* data =', data)


# ===== main program =====
mode = int(input('Enter mode (0 for Queue, -1 for Stack): '))
Queue_or_Stack(mode)