# -*- coding: utf-8 -*-
"""HW3-List Comprehension-111401546.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rr0vekXfGraHAWx_Lk-t0WUN7_5DRjwz
"""

#企管四 111401546 胡予娟
##--------------------------------------------------
# [ Problem ] - 搜尋 小於 n 的質數
# < 解法一 > : in vs. not in - Membership Operators
##--------------------------------------------------
import math

prime_numbers = []        # prime_numbers : 質數
composite_numbers = []    # composite_numbers : 複合數

n = int(input('Enter a Natural number:'))
# Find the composite numbers less than n ...
for i in range(2,math.ceil(math.sqrt(n))):
    for j in range(i*2, n, i):
      if composite_numbers.count(j) > 0:
        break
      else:
        composite_numbers.append(j)


# Exclude the composite numbers from the numbers less than n ...
for x in range(2, n):
    if x not in composite_numbers:
        prime_numbers.append(x)

# ------- print result -------
print('Composite Numbers (<',n,') :' , composite_numbers)
print('\nPrime Numbers (< ',n,') : ', prime_numbers)

#企管四 111401546 胡予娟
##--------------------------------------------------
# [ Problem ] - 搜尋 小於 n 的質數
# < 解法一 > : in vs. not in - Membership Operators
# list comprehension
##--------------------------------------------------
import math

n = int(input('Enter a Natural number:'))
composite_numbers = [
    j for i in range(2,math.ceil(math.sqrt(n)))
    for j in range(i*2, n, i)
]
prime_numbers = [
    x for x in range(2, n)  if x not in composite_numbers
]

# ------- print result -------
print('Composite Numbers (<',n,') :' , composite_numbers)
print('\nPrime Numbers (< ',n,') : ', prime_numbers)